name: Publish App

on:
  push:
    branches: [ main ]

env:
  WORKING_DIRECTORY: CloudSaaSCodingTask
  AZURE_WEBAPP_NAME: CloudSaaSCodingTask2
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use
  PUBLISH_PROFILE: ${{ secrets.AZURE_PUBLISH_PROFILE }}
  
jobs:
  publish:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Install dependencies
      run: |
        dotnet restore
        dotnet test
      
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o 'adminuiapp' 
      
    # Deploy to Azure Web apps staging slot
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ env.PUBLISH_PROFILE }}
        package: '${{ env.WORKING_DIRECTORY }}/adminuiapp'
